name: PR Comment

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get PR template
      id: pr_template
      run: |
        echo "::set-output name=body::$(cat .github/pr_template.md)"

    - name: Add comment to PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: ${{ steps.pr_template.outputs.body }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
